"""add_security_alert_columns

Revision ID: f1d6a878f625
Revises: a8062502ddae
Create Date: 2026-04-07 18:13:41.308211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d6a878f625'
down_revision: Union[str, Sequence[str], None] = 'a8062502ddae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_execution_log', sa.Column('is_security_alert', sa.Boolean(), server_default='false', nullable=False, comment='보안 위반 여부'))
    op.add_column('rag_execution_log', sa.Column('hit_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='감지된 공격 패턴 (JSON Array)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_execution_log', 'hit_patterns')
    op.drop_column('rag_execution_log', 'is_security_alert')
    # ### end Alembic commands ###
