"""add

Revision ID: a817730a5f8d
Revises: init
Create Date: 2026-02-15 04:18:24.260987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'a817730a5f8d'
down_revision: Union[str, Sequence[str], None] = 'init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_chunk',
    sa.Column('content', sa.Text(), nullable=False, comment='chunk text'),
    sa.Column('content_hash', sa.String(length=64), sa.Computed("encode(digest(coalesce(content,''), 'sha256'), 'hex')", persisted=True), nullable=False, comment='auto-generated sha256'),
    sa.Column('chunk_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(content,''))", persisted=True), nullable=False, comment='auto-generated tsvector'),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'chunk_index', 'chunk_version', name='uq_source_chunk_content_hash_chunk_index_chunk_version')
    )
    op.create_index('ix_source_chunk_chunk_tsv_gin', 'source_chunk', ['chunk_tsv'], unique=False, postgresql_using='gin')
    op.create_table('source_fewshot_example',
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('example_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('irt_a', sa.Float(), nullable=True, comment='IRT(discrimination)'),
    sa.Column('irt_b', sa.Float(), nullable=True, comment='IRT(difficulty)'),
    sa.Column('irt_c', sa.Float(), nullable=True, comment='IRT(guessing)'),
    sa.Column('content', sa.Text(), nullable=False, comment='source text'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='processing step'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_fewshot_example table'
    )
    op.create_table('source_interface',
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='source text'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='processing step'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_interface table'
    )
    op.create_table('source_knowledge',
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='source text'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='processing step'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_knowledge table'
    )
    op.create_table('source_prompt_template',
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=True),
    sa.Column('model_size', sa.Float(), nullable=True, comment='Billion'),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('template_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='source text'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='processing step'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_prompt_template table'
    )
    op.create_table('map_source_chunk',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.Enum('prompt_template', 'interface', 'fewshot_example', 'knowledge', name='source_name_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'source_id', 'source_name', name='uq_map_source_chunk_chunk_id_source_id_source_name')
    )
    op.create_index('ix_map_source_chunk_chunk_id', 'map_source_chunk', ['chunk_id'], unique=False)
    op.create_index('ix_map_source_chunk_source_id_source_name', 'map_source_chunk', ['source_id', 'source_name'], unique=False)
    op.create_table('source_chunk_vec',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_vec', Vector(dim=1536), nullable=False),
    sa.Column('vec_model_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'vec_model_name', name='uq_source_chunk_vec_chunk_id_vec_model_name')
    )
    op.create_index('ix_source_chunk_vec_chunk_id', 'source_chunk_vec', ['chunk_id'], unique=False)
    op.create_index('ix_source_chunk_vec_chunk_vec_hnsw', 'source_chunk_vec', ['chunk_vec'], unique=False, postgresql_using='hnsw', postgresql_ops={'chunk_vec': 'vector_cosine_ops'})
    # ### end Alembic commands ###

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_source_chunk_content_bm25
        ON public.source_chunk
        USING bm25 (id, content)
        WITH (key_field='id');
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_chunk_vec_chunk_vec_hnsw', table_name='source_chunk_vec', postgresql_using='hnsw', postgresql_ops={'chunk_vec': 'vector_cosine_ops'})
    op.drop_index('ix_source_chunk_vec_chunk_id', table_name='source_chunk_vec')
    op.drop_table('source_chunk_vec')
    op.drop_index('ix_map_source_chunk_source_id_source_name', table_name='map_source_chunk')
    op.drop_index('ix_map_source_chunk_chunk_id', table_name='map_source_chunk')
    op.drop_table('map_source_chunk')
    op.drop_table('source_prompt_template')
    op.drop_table('source_knowledge')
    op.drop_table('source_interface')
    op.drop_table('source_fewshot_example')
    op.drop_index('ix_source_chunk_chunk_tsv_gin', table_name='source_chunk', postgresql_using='gin')
    op.drop_table('source_chunk')
    # ### end Alembic commands ###

    op.execute("DROP INDEX IF EXISTS ix_source_chunk_content_bm25;")
    op.execute("DROP TYPE source_name_enum CASCADE;")

    